---
- name: WSBcleanup
  hosts: cerberus.CERBERUSNET.NET
  tasks:
    ansible.windows.win_shell:
        cmd: |
          'wbadmin delete backup -keepVersions:30'


#    ansible.windows.win_powershell:
#      script: |
#        # Your PowerShell script content here
#        Write-Host "Hello from Ansible!"
