---
- name: WSBcleanup
  hosts: '{{ target }}'
  tasks:
    - name: cleanup backups and keeping last 30 backups
      ansible.windows.win_shell: |
        cmd: "wbadmin delete backup -keepVersions:30"
